{% set name = "mastercard-client-encryption" %}
{% set version = "1.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mastercard-client-encryption-{{ version }}.tar.gz
  sha256: 76765ce37f569b91962d8055d25a2a0c06d02e80e1b032a0ddb858b902fc1bb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pycryptodome >=3.8.1
    - setuptools >=69.1.0
    - cryptography >=42.0.0

test:
  imports:
    - client_encryption
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Mastercard/client-encryption-python
  summary: Mastercard Client encryption.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
